spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  rabbitmq:
    host: localhost
    port: 5672

eventstore:
  connection-string: esdb://localhost:2113?tls=false
payment:
  api-host: http://localhost:8081

logging:
  level:
    root: info
    eshop.api: debug
    grpc: debug
grpc:
  server:
    port: 9090