spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

logging:
  level:
    root: info
    eshop.api: debug