spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres

eventstore:
  connection-string: esdb://localhost:2113?tls=false

logging:
  level:
    root: info
    eshop.api: debug