apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstore-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore-stateful-set
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eventstore
  template:
    metadata:
      labels:
        component: eventstore
    spec:
      volumes:
        - name: eventstore-storage
          persistentVolumeClaim:
            claimName: eventstore-persistent-volume-claim
      containers:
        - name: eventstore
          image: eventstore/eventstore:22.10.1-alpha-arm64v8
          ports:
            - containerPort: 2113
            - containerPort: 1113
          volumeMounts:
            - mountPath: /usr/data/eventstore
              name: eventstore-storage
          env:
            - name: EVENTSTORE_INT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EVENTSTORE_EXT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EVENTSTORE_CLUSTER_SIZE
              value: '1'
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: 'All'
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: 'true'
            - name: EVENTSTORE_EXT_TCP_PORT
              value: '1113'
            - name: EVENTSTORE_HTTP_PORT
              value: '2113'
            - name: EVENTSTORE_INSECURE
              value: 'true'
            - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
              value: 'true'
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: 'true'
