apiVersion: v1
kind: Service
metadata:
  name: eventstore-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: eventstore
  ports:
    - protocol: 'TCP'
      port: 2113
      targetPort: 2113
  clusterIP: None
