version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: 'no'
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./init-multiple-database.sh:/docker-entrypoint-initdb.d/init-multiple-database.sh.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=product_service,user_service,order_service,inventory_service
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  mongo:
    image: mongo:6.0.3
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

volumes:
  eventstore-volume-data:
  eventstore-volume-logs: