version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: 'no'
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./init-multiple-database.sh:/docker-entrypoint-initdb.d/init-multiple-database.sh.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=product_service,user_service,order_service,inventory_service
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  mongo:
    image: mongo:6.0.3
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo