spring:
  data:
    mongodb:
      database: user-service
      username: mongo
      password: mongo
      port: 27017
      host: localhost
      authentication-database: admin

logging:
  level:
    root: info
    eshop.api: debug
