kind: Service
apiVersion: v1
metadata:
  name: order-service-nodeport-service
spec:
  type: NodePort
  selector:
    component: order-service
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
