kind: Service
apiVersion: v1
metadata:
  name: order-service-svc
spec:
  type: ClusterIP
  selector:
    component: order-service
  ports:
    - port: 80
      targetPort: 8080
      name: 'http-port'
    - port: 9090
      targetPort: 9090
      name: 'grpc-port'
