package eshop.orderservice.statemachine;

public enum OrderEvent {
    MAKE_PAYMENT, PAYMENT_SUCCESS, PAYMENT_FAILED,
    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_PASSED, ALLOCATION_FAILED,
    DELIVERY_ORDER, DELIVERY_SUCCESS, DELIVERY_FAILED
}