spring.datasource.url=jdbc:postgresql://localhost:5432/product_service
#spring.datasource.url=jdbc:h2:mem:testdb;MODE=POSTGRESQL
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.sql.init.platform=postgres
#spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.flyway.enabled=true
spring.jpa.show-sql=true
logging.level.root=info
logging.level.eshop.api=debug