kind: Service
apiVersion: v1
metadata:
  name: postgres-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
      name: sql-port
