server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres

logging:
  level:
    root: info
    eshop.api: debug