kind: Service
apiVersion: v1
metadata:
  name: inventory-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: inventory-service
  ports:
    - port: 80
      targetPort: 8080
    - port: 9090
      targetPort: 9090
