apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: product-service
  template:
    metadata:
      labels:
        component: product-service
    spec:
      containers:
        - name: product-service
          image: kkhanhluu/product-service:0.0.16
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring":{"datasource":{"url":"jdbc:postgresql://postgres-cluster-ip-service:5432/product_service","username":"postgres","password":"postgres","driver-class-name":"org.postgresql.Driver"},"sql":{"init":{"platform":"postgres"}}}}'
