apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: product-service
  template:
    metadata:
      labels:
        component: product-service
    spec:
      containers:
        - name: product-service
          image: kkhanhluu/product-service:0.0.16
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring":{"data":{"mongodb":{"host":"mongo-cluster-ip-service","username":"mongo","password":"mongo","database":"payment-service","port":27017,"authentication-database":"admin"}}}}'
