package eshop.orderservice.order.query.entity;

public enum OrderStatus {
    CREATED,
    PAYMENT_PENDING, PAID, PAYMENT_EXCEPTION,
    VALIDATION_PENDING, VALIDATED, VALIDATION_EXCEPTION,
    ALLOCATION_PENDING, ALLOCATED, ALLOCATION_EXCEPTION,
    BEING_DELIVERED, DELIVERED, DELIVERY_EXCEPTION
}