kind: Service
apiVersion: v1
metadata:
  name: user-service-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: user-service
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30090
