kind: Service
apiVersion: v1
metadata:
  name: user-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: user-service
  ports:
    - port: 80
      targetPort: 8080
      name: 'http-port'
    - port: 9090
      targetPort: 9090
      name: 'grpc-port'
