package eshop.orderservice.order.saga;

public enum OrderStateMachineEvent {
    CREATE,
    PAYMENT_SUCCESS, PAYMENT_FAILED,
    VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_PASSED, ALLOCATION_FAILED,
}