name: CI
on:
  pull_request:
    types: [opened]

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - run: yarn install --frozen-lockfile

      - run: npx nx workspace-lint

      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=verify --parallel=3