name: Publish
on:
  push:
    tags:
      - '@**'
env:
  dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "release_version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get image name and version
        run: |
          STR=${release_version:1}
          POSTFIX="-app"
          POSTFIX_LIB="-lib"
          CONTAINER_NAME_STR=$(echo $STR | cut -d '/' -f 1)
          CONTAINER_NAME=${CONTAINER_NAME_STR%$POSTFIX}
          CONTAINER_NAME_LIB=${CONTAINER_NAME_STR%$POSTFIX_LIB}
          TAG=$(echo $STR | cut -d '/' -f 2)
          VERSION=${TAG:1}
          echo "container_name=$(echo $CONTAINER_NAME)" >> $GITHUB_ENV
          echo "container_name_lib=$(echo $CONTAINER_NAME_LIB)" >> $GITHUB_ENV
          echo "version=$(echo $VERSION)" >> $GITHUB_ENV 

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set up Docker Buildx
        if: ${{ contains(github.ref_name, 'app') }}
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        if: ${{ contains(github.ref_name, 'app') }}
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Container Registry
        if: ${{ contains(github.ref_name, 'app') }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish docker images to docker hub
        if: ${{ contains(github.ref_name, 'app') }}
        run: |
          cd ./apps/$container_name
          mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B spring-boot:build-image
          docker push docker.io/$dockerhub_username/$container_name:$version
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Publish libraries
        if: ${{ contains(github.ref_name, 'lib') }}
        run: |
          cd ./libs/$container_name_lib
          mvn -B -Pgithub deploy
          cd ../..
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}