name: Release
on:
  push:
    branches:
      main
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    #    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - run: yarn install --frozen-lockfile

      - name: Git config
        run: |
          git config --local user.email "kkhanhluu@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Raise version of affected libraries
        run: |
          LIBS=$(npx nx affected:libs --base=$NX_BASE --head=$NX_HEAD --plain)
          for LIBRARY in $LIBS
          do
            cd ./libs/$LIBRARY
            npx @dwmkerr/standard-version --packageFiles ./pom.xml --bumpFiles ./pom.xml -t @$LIBRARY-lib/v
            echo "Bumping $LIBRARY"
            cd ../..
          done

      - name: Raise version of affected apps
        run: |
          APPS=$(npx nx affected:apps --base=$NX_BASE --head=$NX_HEAD --plain)
          for APP in $APPS
          do
            cd ./apps/$APP
            npx @dwmkerr/standard-version --packageFiles ./pom.xml --bumpFiles ./pom.xml -t @$APP-app/v
            echo "Bumping $APP"
            cd ../..
          done

      - name: Release tags
        uses: ad-m/github-push-action@master
        with:
          force: true
          tags: true
          github_token: ${{ secrets.GIT_TOKEN }}